export {default as Hero} from './Hero.jsx'
export {default as About} from './About.jsx'
export {default as Projects} from './Projects.jsx'
export {default as Experience} from './Experience.jsx'
export {default as Testimonials} from './Testimonials.jsx'
export {default as Contact} from './Contact.jsx'
